import sys, getopt, cv2
from scripts import decode, encode

def main(argv):
	input_file = ''
	path = './'
	to_encode = True

	try:
		opts, args = getopt.getopt(argv,"hedi:o:")
	except getopt.GetoptError:
		print('main.py [-e (for encode) | -d (for decode)] -i <inputfile> -o <outputpath>')
		sys.exit(2)

	for opt, arg in opts:
		if opt == '-h':
			print('main.py [commands]')
			print('-e: For encode the image')
			print('-d: For decode the image')
			print('-i: Image input to the program')
			print('-o: Path to save the image generated by the program')
			print('-h: List the commands')
			sys.exit()
		elif opt in ("-i"):
			input_file = arg
		elif opt in ("-o"):
			path = arg
		elif opt in ("-e"):
			to_encode = True
		elif opt in ("-d"):
			to_encode = False

	if input_file == '':
		print('main.py [-e (for encode) | -d (for decode)] -i <inputfile> -o <outputpath>')
		sys.exit(2)

	try:
		if to_encode == True:
			encode.encode(input_file, path)
		else:
			decode.decode(input_file, path)
	except Exception as inst:
		print(type(inst))
		print(inst.args)
		print(inst)

if __name__ == '__main__':
	main(sys.argv[1:])